import ast, subprocess, sys
from pathlib import Path
from hsf.foundry.compiler import compile_spec

def test_template_engine_compiles_and_is_byte_stable(spec_and_sha):
    spec, sha = spec_and_sha
    a, _ = compile_spec(spec, sha, engine="template")
    b, _ = compile_spec(spec, sha, engine="template")
    assert a == b and "AUTO-GENERATED by HSF Foundry" in a
    ast.parse(a)

def test_exactly_one_llm_call_per_attempt(spec_and_sha, monkeypatch):
    from hsf.foundry import llm_client
    calls = {"n": 0}
    def fake(system, user, model="m"):
        calls["n"] += 1
        from hsf.foundry.compiler import render_artifact
        spec, sha = spec_and_sha
        return render_artifact(spec, sha, "llm")
    monkeypatch.setattr(llm_client, "complete", fake)
    spec, sha = spec_and_sha
    compile_spec(spec, sha, engine="llm")
    assert calls["n"] == 1

def test_runtime_package_cannot_import_foundry():
    code = ("import sys, hsf.runtime, hsf.runtime.orchestrator, hsf.runtime.sandwich; "
            "bad=[m for m in sys.modules if m.startswith('hsf.foundry')]; "
            "sys.exit(1 if bad else 0)")
    r = subprocess.run([sys.executable, "-c", code], cwd=Path(__file__).resolve().parents[1],
                       capture_output=True)
    assert r.returncode == 0, r.stderr.decode()

def test_trace_backrefs_present(artifact_source):
    assert artifact_source.count("trace=") >= 4  # guards + rules all carry spec back-references
